#! /usr/bin/env bash

DEBUG=${DEBUG:-0}

debug() {
    [[ $DEBUG -eq 1 ]] && echo "[DEBUG] $*" >&2
}

# get base directory
BASE="$(dirname $(realpath "${BASH_SOURCE[0]}"))"
debug "BASE: $BASE"

# get current year
YEAR=$(date +%Y)
debug "YEAR: $YEAR"

# get next day serial number, i.e. if last is day-05, next is day-06
LAST=$(ls "$BASE/$YEAR" | grep -E '^day-[0-9]{2}$' | sort -n | tail -1)
NEXT=$(printf "%02d" $((10#${LAST##*-} + 1)))
debug "LAST: $LAST"
debug "NEXT: $NEXT"

# create new day directory
mkdir "$BASE/$YEAR/day-$NEXT"

# create boilerplate files
echo 's = open("input.txt").read()' > "$BASE/$YEAR/day-$NEXT/day-$NEXT.py"
touch "$BASE/$YEAR/day-$NEXT/input.txt"
